export const slugify = str => str.toLowerCase()
.trim()
.replace('é', 'e')
.replace('è', 'e')
.replace('ê', 'e')
.replace('ù', 'u')
.replace('û', 'u')
.replace('ô', 'o')
.replace('ï', 'i')
.replace('ç', 'c')
.replace('à', 'a')
.replace(/[^\w\s-]/g, '')
.replace(/[\s_-]+/g, '-')
.replace(/^-+|-+$/g, '');